"""empty message

Revision ID: 16b1a782cb5e
Revises: 1455822092f3
Create Date: 2018-09-24 15:41:26.807867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b1a782cb5e'
down_revision = '1455822092f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('invoice', sa.String(length=255), nullable=True),
    sa.Column('invoice_type', sa.String(length=255), nullable=True),
    sa.Column('invoice_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('financier', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=255), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('added_to_stock', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['specifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'order_id', 'lot_number', name='unique_order_item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
